# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gdo/Developpement/Informatique/Personnel/cogip/avoidance

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gdo/Developpement/Informatique/Personnel/cogip/avoidance

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gdo/Developpement/Informatique/Personnel/cogip/avoidance/CMakeFiles /home/gdo/Developpement/Informatique/Personnel/cogip/avoidance//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gdo/Developpement/Informatique/Personnel/cogip/avoidance/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cogip_api

# Build rule for target.
cogip_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cogip_api
.PHONY : cogip_api

# fast build rule for target.
cogip_api/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/build
.PHONY : cogip_api/fast

lib/avoidance/avoidance.o: lib/avoidance/avoidance.cpp.o
.PHONY : lib/avoidance/avoidance.o

# target to build an object file
lib/avoidance/avoidance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/avoidance/avoidance.cpp.o
.PHONY : lib/avoidance/avoidance.cpp.o

lib/avoidance/avoidance.i: lib/avoidance/avoidance.cpp.i
.PHONY : lib/avoidance/avoidance.i

# target to preprocess a source file
lib/avoidance/avoidance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/avoidance/avoidance.cpp.i
.PHONY : lib/avoidance/avoidance.cpp.i

lib/avoidance/avoidance.s: lib/avoidance/avoidance.cpp.s
.PHONY : lib/avoidance/avoidance.s

# target to generate assembly for a file
lib/avoidance/avoidance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/avoidance/avoidance.cpp.s
.PHONY : lib/avoidance/avoidance.cpp.s

lib/cogip_defs/Coords.o: lib/cogip_defs/Coords.cpp.o
.PHONY : lib/cogip_defs/Coords.o

# target to build an object file
lib/cogip_defs/Coords.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/cogip_defs/Coords.cpp.o
.PHONY : lib/cogip_defs/Coords.cpp.o

lib/cogip_defs/Coords.i: lib/cogip_defs/Coords.cpp.i
.PHONY : lib/cogip_defs/Coords.i

# target to preprocess a source file
lib/cogip_defs/Coords.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/cogip_defs/Coords.cpp.i
.PHONY : lib/cogip_defs/Coords.cpp.i

lib/cogip_defs/Coords.s: lib/cogip_defs/Coords.cpp.s
.PHONY : lib/cogip_defs/Coords.s

# target to generate assembly for a file
lib/cogip_defs/Coords.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/cogip_defs/Coords.cpp.s
.PHONY : lib/cogip_defs/Coords.cpp.s

lib/obstacles/Circle.o: lib/obstacles/Circle.cpp.o
.PHONY : lib/obstacles/Circle.o

# target to build an object file
lib/obstacles/Circle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/Circle.cpp.o
.PHONY : lib/obstacles/Circle.cpp.o

lib/obstacles/Circle.i: lib/obstacles/Circle.cpp.i
.PHONY : lib/obstacles/Circle.i

# target to preprocess a source file
lib/obstacles/Circle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/Circle.cpp.i
.PHONY : lib/obstacles/Circle.cpp.i

lib/obstacles/Circle.s: lib/obstacles/Circle.cpp.s
.PHONY : lib/obstacles/Circle.s

# target to generate assembly for a file
lib/obstacles/Circle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/Circle.cpp.s
.PHONY : lib/obstacles/Circle.cpp.s

lib/obstacles/List.o: lib/obstacles/List.cpp.o
.PHONY : lib/obstacles/List.o

# target to build an object file
lib/obstacles/List.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/List.cpp.o
.PHONY : lib/obstacles/List.cpp.o

lib/obstacles/List.i: lib/obstacles/List.cpp.i
.PHONY : lib/obstacles/List.i

# target to preprocess a source file
lib/obstacles/List.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/List.cpp.i
.PHONY : lib/obstacles/List.cpp.i

lib/obstacles/List.s: lib/obstacles/List.cpp.s
.PHONY : lib/obstacles/List.s

# target to generate assembly for a file
lib/obstacles/List.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/List.cpp.s
.PHONY : lib/obstacles/List.cpp.s

lib/obstacles/Obstacle.o: lib/obstacles/Obstacle.cpp.o
.PHONY : lib/obstacles/Obstacle.o

# target to build an object file
lib/obstacles/Obstacle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/Obstacle.cpp.o
.PHONY : lib/obstacles/Obstacle.cpp.o

lib/obstacles/Obstacle.i: lib/obstacles/Obstacle.cpp.i
.PHONY : lib/obstacles/Obstacle.i

# target to preprocess a source file
lib/obstacles/Obstacle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/Obstacle.cpp.i
.PHONY : lib/obstacles/Obstacle.cpp.i

lib/obstacles/Obstacle.s: lib/obstacles/Obstacle.cpp.s
.PHONY : lib/obstacles/Obstacle.s

# target to generate assembly for a file
lib/obstacles/Obstacle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/Obstacle.cpp.s
.PHONY : lib/obstacles/Obstacle.cpp.s

lib/obstacles/ObstaclePolygon.o: lib/obstacles/ObstaclePolygon.cpp.o
.PHONY : lib/obstacles/ObstaclePolygon.o

# target to build an object file
lib/obstacles/ObstaclePolygon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/ObstaclePolygon.cpp.o
.PHONY : lib/obstacles/ObstaclePolygon.cpp.o

lib/obstacles/ObstaclePolygon.i: lib/obstacles/ObstaclePolygon.cpp.i
.PHONY : lib/obstacles/ObstaclePolygon.i

# target to preprocess a source file
lib/obstacles/ObstaclePolygon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/ObstaclePolygon.cpp.i
.PHONY : lib/obstacles/ObstaclePolygon.cpp.i

lib/obstacles/ObstaclePolygon.s: lib/obstacles/ObstaclePolygon.cpp.s
.PHONY : lib/obstacles/ObstaclePolygon.s

# target to generate assembly for a file
lib/obstacles/ObstaclePolygon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/ObstaclePolygon.cpp.s
.PHONY : lib/obstacles/ObstaclePolygon.cpp.s

lib/obstacles/ObstacleRectangle.o: lib/obstacles/ObstacleRectangle.cpp.o
.PHONY : lib/obstacles/ObstacleRectangle.o

# target to build an object file
lib/obstacles/ObstacleRectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/ObstacleRectangle.cpp.o
.PHONY : lib/obstacles/ObstacleRectangle.cpp.o

lib/obstacles/ObstacleRectangle.i: lib/obstacles/ObstacleRectangle.cpp.i
.PHONY : lib/obstacles/ObstacleRectangle.i

# target to preprocess a source file
lib/obstacles/ObstacleRectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/ObstacleRectangle.cpp.i
.PHONY : lib/obstacles/ObstacleRectangle.cpp.i

lib/obstacles/ObstacleRectangle.s: lib/obstacles/ObstacleRectangle.cpp.s
.PHONY : lib/obstacles/ObstacleRectangle.s

# target to generate assembly for a file
lib/obstacles/ObstacleRectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/ObstacleRectangle.cpp.s
.PHONY : lib/obstacles/ObstacleRectangle.cpp.s

lib/obstacles/obstacles.o: lib/obstacles/obstacles.cpp.o
.PHONY : lib/obstacles/obstacles.o

# target to build an object file
lib/obstacles/obstacles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/obstacles.cpp.o
.PHONY : lib/obstacles/obstacles.cpp.o

lib/obstacles/obstacles.i: lib/obstacles/obstacles.cpp.i
.PHONY : lib/obstacles/obstacles.i

# target to preprocess a source file
lib/obstacles/obstacles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/obstacles.cpp.i
.PHONY : lib/obstacles/obstacles.cpp.i

lib/obstacles/obstacles.s: lib/obstacles/obstacles.cpp.s
.PHONY : lib/obstacles/obstacles.s

# target to generate assembly for a file
lib/obstacles/obstacles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/obstacles/obstacles.cpp.s
.PHONY : lib/obstacles/obstacles.cpp.s

lib/path/Pose.o: lib/path/Pose.cpp.o
.PHONY : lib/path/Pose.o

# target to build an object file
lib/path/Pose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/path/Pose.cpp.o
.PHONY : lib/path/Pose.cpp.o

lib/path/Pose.i: lib/path/Pose.cpp.i
.PHONY : lib/path/Pose.i

# target to preprocess a source file
lib/path/Pose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/path/Pose.cpp.i
.PHONY : lib/path/Pose.cpp.i

lib/path/Pose.s: lib/path/Pose.cpp.s
.PHONY : lib/path/Pose.s

# target to generate assembly for a file
lib/path/Pose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/path/Pose.cpp.s
.PHONY : lib/path/Pose.cpp.s

lib/utils/utils.o: lib/utils/utils.cpp.o
.PHONY : lib/utils/utils.o

# target to build an object file
lib/utils/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/utils/utils.cpp.o
.PHONY : lib/utils/utils.cpp.o

lib/utils/utils.i: lib/utils/utils.cpp.i
.PHONY : lib/utils/utils.i

# target to preprocess a source file
lib/utils/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/utils/utils.cpp.i
.PHONY : lib/utils/utils.cpp.i

lib/utils/utils.s: lib/utils/utils.cpp.s
.PHONY : lib/utils/utils.s

# target to generate assembly for a file
lib/utils/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cogip_api.dir/build.make CMakeFiles/cogip_api.dir/lib/utils/utils.cpp.s
.PHONY : lib/utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cogip_api"
	@echo "... lib/avoidance/avoidance.o"
	@echo "... lib/avoidance/avoidance.i"
	@echo "... lib/avoidance/avoidance.s"
	@echo "... lib/cogip_defs/Coords.o"
	@echo "... lib/cogip_defs/Coords.i"
	@echo "... lib/cogip_defs/Coords.s"
	@echo "... lib/obstacles/Circle.o"
	@echo "... lib/obstacles/Circle.i"
	@echo "... lib/obstacles/Circle.s"
	@echo "... lib/obstacles/List.o"
	@echo "... lib/obstacles/List.i"
	@echo "... lib/obstacles/List.s"
	@echo "... lib/obstacles/Obstacle.o"
	@echo "... lib/obstacles/Obstacle.i"
	@echo "... lib/obstacles/Obstacle.s"
	@echo "... lib/obstacles/ObstaclePolygon.o"
	@echo "... lib/obstacles/ObstaclePolygon.i"
	@echo "... lib/obstacles/ObstaclePolygon.s"
	@echo "... lib/obstacles/ObstacleRectangle.o"
	@echo "... lib/obstacles/ObstacleRectangle.i"
	@echo "... lib/obstacles/ObstacleRectangle.s"
	@echo "... lib/obstacles/obstacles.o"
	@echo "... lib/obstacles/obstacles.i"
	@echo "... lib/obstacles/obstacles.s"
	@echo "... lib/path/Pose.o"
	@echo "... lib/path/Pose.i"
	@echo "... lib/path/Pose.s"
	@echo "... lib/utils/utils.o"
	@echo "... lib/utils/utils.i"
	@echo "... lib/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

